import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillLinkedin, AiFillGithub} from 'react-icons/ai';
import Image from "next/image";
import deved from "../public/avatar2.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import ozei from '../public/Ozei-mobile.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import {useState} from "react";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title>Mattias Velamsson Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bh-white px-10 dark:bg-darkBase md:px-20 lg:px-40 scroll-smooth'>
      {/* Top Section Start */}
      <section className="min-h-screen">
      <nav className="p-10 mb-12 flex justify-between dark:text-white">
        <h1 className='text-xl font-burtons'>smackdh</h1>
        <ul className='flex items-center'>
          <li>
            <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl  dark:text-white'/>
          </li>
          <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 border-none" href="#">Resume</a></li>
        </ul>
        </nav>
        {/* Profile Info */}
        <div className='text-center p-10 py-10'>
            <h2 className='text-5xl py-2 text-teal-500 font-medium md:text-6xl'>
            Mattias Velamsson
            </h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>
            Fullstack Developer
            </h3>
            <p className='text-md py-5 md:text-xl leading-6 text-gray-800 max-w-xl mx-auto dark:text-white'>
              Hey, Im Mattias!
              I used to work as a technical engineer and team leader back in Sweden for 7 years. I graduated from LeWagon bootcamp during winter 2022 and am now looking forward to new challenges in my career-path!
              Hit me up on LinkedIn or by mail if youd like to know more about me or have any questions!
            </p>
        </div>
        {/* Links to socials */}
        <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-teal-500'>
            <AiFillGithub/>
            <AiFillLinkedin/>
        </div>
        <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
        <Image src={deved} layout="fill" objectFit="cover"/>
        </div>
      </section>
      {/* Top Section End */}
      <section>
      <div className='text-center py-10'>
        <h3 className="text-3xl py-1 dark:text-white">Services I offer</h3>
        <p className='text-md py-2 leading-6 text-gray-80  dark:text-white'>What I've been working on.....
        <span className='text-teal-500'> Ozei </span>
        a group project of 4 people, creating and deploying a working Prototype in 2 weeks.
        </p>
        <p className='text-md py-2 leading-6 text-gray-80  dark:text-white'>This is some more informational text....
        <span className='text-teal-500'> Subject </span>
        Put something interesting and important here..
        </p>
      </div>
      {/* Card One */}
      <div className='lg:flex gap-10 justify-center'>
        <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
          <Image className="mx-auto" src={design} width={100} height={100}/>
          <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
          <p className='py-2'>I make some sick ass designs.</p>
          <h4 className='py-4 text-teal-600'>Technologies used</h4>
          <p className='text-gray-800 py-1'>Ruby</p>
          <p className='text-gray-800 py-1'>Ruby on Rails</p>
          <p className='text-gray-800 py-1'>JavaScript</p>
        </div>
      {/* Card Two */}
        <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white">
          <Image className="mx-auto" src={code} width={100} height={100}/>
          <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
          <p className='py-2'>I make some sick ass designs.</p>
          <h4 className='py-4 text-teal-600'>Technologies used</h4>
          <p className='text-gray-800 py-1'>Ruby</p>
          <p className='text-gray-800 py-1'>Ruby on Rails</p>
          <p className='text-gray-800 py-1'>JavaScript</p>
        </div>
      {/* Card Three */}
        <div className='text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white'>
          <Image className="mx-auto" src={consulting} width={100} height={100}/>
          <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
          <p className='py-2'>I make some sick ass designs.</p>
          <h4 className='py-4 text-teal-600'>Technologies used</h4>
          <p className='text-gray-800 py-1'>Ruby</p>
          <p className='text-gray-800 py-1'>Ruby on Rails</p>
          <p className='text-gray-800 py-1'>JavaScript</p>
        </div>
      </div>
      <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
        <div className='basis-1/3 flex-1'>
          <Image src={ozei} className="rounded-lg object-cover" width={"10%"} height={"10%"} layout="responsive"/>
        </div>
        <div className='basis-1/3 flex-1'>
         <Image src={web2} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive"/>
        </div>
      </div>
      </section>
      </main>
    </div>
  );
}
